# Project information
site_name: Kubelinux.io
site_url: https://kubelinux.io
site_author: Kubelinux Team

# Repository
repo_name: kubelinux-io/kubelinux.io
repo_url: https://github.com/kubelinux-io/kubelinux.io

# Copyright
copyright: Copyright &copy; 2016 - 2024 Kubelinux Team

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    - content.action.edit

edit_uri: edit/main/docs/